
name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: silent

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: silent
        path: silent/dist/windows

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: wizard

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: wizard
        path: wizard/dist/windows